import type { AvatarStyleMeta } from './types';

/**
 * DevImage 自研 native 头像风格目录
 */
export const NATIVE_STYLE_CATALOG: readonly AvatarStyleMeta[] = [
  {
    id: 'devimg',
    title: '图即头像',
    group: 'gradient',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
    queryParams: ['variant', 'text', 'shape', 'bg', 'fg', 'pattern'],
  },
  {
    id: 'devimg-geo',
    title: '几何弧环',
    group: 'geometric',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-pattern',
    title: '纹理 pattern',
    group: 'geometric',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
    queryParams: ['text', 'shape', 'fg', 'pattern'],
  },
  {
    id: 'devimg-gradient',
    title: '渐变圆',
    group: 'gradient',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
    aliasOf: 'devimg',
    queryParams: ['text', 'shape', 'bg', 'fg'],
  },
  {
    id: 'devimg-mesh',
    title: '网格渐变',
    group: 'gradient',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
    aliasOf: 'devimg',
    queryParams: ['text', 'shape', 'bg', 'fg'],
  },
  {
    id: 'devimg-initials',
    title: '渐变首字',
    group: 'text',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
    aliasOf: 'devimg',
    queryParams: ['variant', 'shape', 'bg', 'fg'],
  },
  {
    id: 'devimg-mandala',
    title: '曼陀罗',
    group: 'abstract',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-topo',
    title: '等高线地形',
    group: 'abstract',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-hash',
    title: '哈希色条',
    group: 'abstract',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-matrix',
    title: '类 QR 矩阵',
    group: 'abstract',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-bubbles',
    title: '圆堆积',
    group: 'geometric',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-radical',
    title: '部首纹理',
    group: 'text',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-pixel',
    title: '抽象像素',
    group: 'retro',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-glass',
    title: '玻璃拟态',
    group: 'filter',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-neon',
    title: '霓虹描边',
    group: 'filter',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-paper',
    title: '纸雕',
    group: 'filter',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-riso',
    title: 'Risograph',
    group: 'filter',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-bot',
    title: '极简机器人',
    group: 'symbol',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-face',
    title: '表情符号',
    group: 'symbol',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
  {
    id: 'devimg-flower',
    title: '花朵',
    group: 'symbol',
    engine: 'native',
    license: 'DevImage',
    provider: 'devimage',
  },
] as const;
