import type { AvatarStyleMeta } from './types';

/**
 * 第三方 partner 引擎风格（当前为 DiceBear）
 */
export const PARTNER_STYLE_CATALOG: readonly AvatarStyleMeta[] = [
  {
    id: 'rings',
    title: 'Rings',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'identicon',
    title: 'Identicon',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'shapes',
    title: 'Shapes',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'stripes',
    title: 'Stripes',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'triangles',
    title: 'Triangles',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'glass',
    title: 'Glass',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'disco',
    title: 'Disco',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'shape-grid',
    title: 'Shape Grid',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'thumbs',
    title: 'Thumbs',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'pixel-art',
    title: 'Pixel Art',
    group: 'pixel',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'pixel-art-neutral',
    title: 'Pixel Art Neutral',
    group: 'pixel',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'lorelei',
    title: 'Lorelei',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'lorelei-neutral',
    title: 'Lorelei Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'notionists',
    title: 'Notionists',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'notionists-neutral',
    title: 'Notionists Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'open-peeps',
    title: 'Open Peeps',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'avataaars',
    title: 'Avataaars',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · avataaars.com',
  },
  {
    id: 'bottts',
    title: 'Bottts',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · bottts.com',
  },
  {
    id: 'adventurer',
    title: 'Adventurer',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Lisa Wischofsky',
  },
  {
    id: 'micah',
    title: 'Micah',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Micah Lanier',
  },
  {
    id: 'icons',
    title: 'Bootstrap Icons',
    group: 'icon',
    engine: 'partner',
    license: 'MIT',
    provider: 'dicebear',
  },
] as const;
