import type { AvatarStyleMeta } from './types';

/**
 * 第三方 partner 引擎风格（当前为 DiceBear）
 */
export const PARTNER_STYLE_CATALOG: readonly AvatarStyleMeta[] = [
  {
    id: 'rings',
    title: 'Rings',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'identicon',
    title: 'Identicon',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'shapes',
    title: 'Shapes',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'stripes',
    title: 'Stripes',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'triangles',
    title: 'Triangles',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'glass',
    title: 'Glass',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'disco',
    title: 'Disco',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'shape-grid',
    title: 'Shape Grid',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'thumbs',
    title: 'Thumbs',
    group: 'geometric',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'pixel-art',
    title: 'Pixel Art',
    group: 'pixel',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'pixel-art-neutral',
    title: 'Pixel Art Neutral',
    group: 'pixel',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'lorelei',
    title: 'Lorelei',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'lorelei-neutral',
    title: 'Lorelei Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'notionists',
    title: 'Notionists',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'notionists-neutral',
    title: 'Notionists Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'open-peeps',
    title: 'Open Peeps',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'avataaars',
    title: 'Avataaars',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · avataaars.com',
  },
  {
    id: 'bottts',
    title: 'Bottts',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · bottts.com',
  },
  {
    id: 'adventurer',
    title: 'Adventurer',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Lisa Wischofsky',
  },
  {
    id: 'micah',
    title: 'Micah',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Micah Lanier',
  },
  {
    id: 'icons',
    title: 'Bootstrap Icons',
    group: 'icon',
    engine: 'partner',
    license: 'MIT',
    provider: 'dicebear',
  },
  {
    id: 'initials',
    title: 'Initials',
    group: 'text',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'initial-face',
    title: 'Initial Face',
    group: 'text',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'croodles',
    title: 'Croodles',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'croodles-neutral',
    title: 'Croodles Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'fun-emoji',
    title: 'Fun Emoji',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'glyphs',
    title: 'Glyphs',
    group: 'icon',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'miniavs',
    title: 'Miniavs',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'toon-head',
    title: 'Toon Head',
    group: 'character',
    engine: 'partner',
    license: 'CC0-1.0',
    provider: 'dicebear',
  },
  {
    id: 'bottts-neutral',
    title: 'Bottts Neutral',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · bottts.com',
  },
  {
    id: 'avataaars-neutral',
    title: 'Avataaars Neutral',
    group: 'character',
    engine: 'partner',
    license: 'Free commercial',
    provider: 'dicebear',
    attribution: 'Pablo Stanley · avataaars.com',
  },
  {
    id: 'adventurer-neutral',
    title: 'Adventurer Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Lisa Wischofsky',
  },
  {
    id: 'personas',
    title: 'Personas',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Draftbit',
  },
  {
    id: 'big-smile',
    title: 'Big Smile',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Ashley Seaman · The Visual Team',
  },
  {
    id: 'big-ears',
    title: 'Big Ears',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'The Visual Team',
  },
  {
    id: 'big-ears-neutral',
    title: 'Big Ears Neutral',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'The Visual Team',
  },
  {
    id: 'dylan',
    title: 'Dylan',
    group: 'character',
    engine: 'partner',
    license: 'CC BY 4.0',
    provider: 'dicebear',
    attribution: 'Dylan S',
  },
  {
    id: 'jdenticon',
    title: 'Jdenticon',
    group: 'geometric',
    engine: 'partner',
    license: 'MIT',
    provider: 'jdenticon',
    attribution: 'Daniel Mietchen · jdenticon.com',
  },
  {
    id: 'minidenticon',
    title: 'Minidenticon',
    group: 'geometric',
    engine: 'partner',
    license: 'MIT',
    provider: 'minidenticons',
    attribution: 'Roba · github.com/laem/minidenticons',
  },
] as const;
